### ISSUE TITLE
Upgrading to vlitejs@6 in jsdelivr.net doesn't work.

### ISSUE THREAD

**Issue by ignl** [vlitejs/vlite#120]
### Describe the bug

Version 5 works but when I update to version 6 I receive ReferenceError: Vlitejs is not defined.

> 

### Steps to reproduce

<script src="https://cdn.jsdelivr.net/npm/vlitejs@6" crossorigin></script>

### Expected behavior

Can access Vlitejs function after import in v6.

### Vlite.js

6.0.1

### Browser

Any

### OS

Linux

**Comment by yoriiis** [comment]
Hello @ignl, thanks for the report.

Vlitejs version 6 is ESM only, as explained in [CHANGELOG.md](https://github.com/vlitejs/vlite/blob/main/CHANGELOG.md#600). This is a radical change because not all projects are ready to move to EcmaScript modules yet, but that's where we are heading.

Documentation for use with a CDN describes the use case
https://github.com/vlitejs/vlite?tab=readme-ov-file#cdn

If you cannot migrate your project to ESM, you can perfectly keep version 5, it is stable.

**Comment by ignl** [comment]
Ah OK thanks! Missed that.
