### ISSUE TITLE
Third-party cookies and 'postMessage' error.

### ISSUE THREAD

**Issue by abvas** [vlitejs/vlite#123]
### Describe the bug

For Youtube, Vimeo, Dailymotion providers I receive a warning:

`Third-party cookies will be blocked. Learn more in the Issues tab.`

![Image 82](https://github.com/vlitejs/vlite/assets/47285364/e625d0c7-ef37-4bda-858e-9755118dc5d5)

In addition, for the Youtube provider, sometimes I get an error similar to this:

`www-widgetapi.js:1260 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('https://vlite. js.org')`

![Image 83](https://github.com/vlitejs/vlite/assets/47285364/7d2ae4ae-4a9c-4959-a255-0bc314a3bb55)

### Steps to reproduce

Both errors can also be seen on your demo page: https://vlite.js.org/

Just look at the warning and error output for different providers.

Please tell me, is it possible to somehow remove this?

Thank you.

### Expected behavior

No errors or warnings in the console.

### Vlite.js

vlitejs 6.0.2

### Browser

Chrome 121.0.6167.189

### OS

?

**Comment by yoriiis** [comment]
Hi @abvas, thanks for your comments.

The first one is displayed by the SDK of the provider that uses third-party cookies, not by Vlitejs. I haven't reproduced the warning, but I've seen it in the past, nothing serious and there's nothing I can do to fix it I think.
The cookie policy is currently being changed (https://developers.google.com/privacy-sandbox/3pcd). 

The second can be fixed by Vlitejs!
