### ISSUE TITLE
Clear providers and plugins on destroy

### ISSUE THREAD

**Issue by v-stempel** [vlitejs/vlite#79]
### Describe the proposed feature.

Hi, I propose to clear providers and plugins on player destroy, because on SPA it causes an error that provider/plugin already registered.

### Describe alternatives you've considered

As alternative - don't throw the error when prividers/plugins are registered and just ignore registration.

**Comment by yoriiis** [comment]
Hello @v-stempel, after digging I will revert the #83 because it's not within the scope of the destroy function.

The error is throw when the `registerPlugin` or `registerProvider` function is called multiple times. Player initialization and plugin/provider registration are two different steps.

In an SPA, the registration must be done only once. I think it's just a problem in the implementation.
